# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pg7PJ3wsvTrM8E-_PDIDOxuz2OB-WPBU
"""

#1. Create a greeting for your program.

#2. Ask the user for the city that they grew up in.

#3. Ask the user for the name of a pet.

#4. Combine the name of their city and pet and show them their band name.

#5. Make sure the input cursor shows on a new line:



print("Welcomr to the Band Name Generator")
city = input("What is the name of the city you grew up in?\n")
pet = input("What is the name of the pet?\n")
print("Your band name could be " +city + " " +pet)

