# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FQhABaHBbpySaEg4S_UgtRQzMk7tDnip
"""

# There are two variables, a and b from input
a = input()
b = input()
# 🚨 Don't change the code above ☝️
####################################
# Write your code below this line 👇
x = a
a = b
b = x



# 🚨 Don't change the code below 👇
print("a: " + a)
print("b: " + b)

